/* ============================================================
   Content Constructor — core/schema.js
   JSON Спецификация блоков и настроек проекта
   ============================================================ */

const CC_SCHEMA_SPEC = {
    description: "This JSON defines the layout and content of a web page constructor. You can modify the title, slug, theme, and blocks. When adding or editing blocks, follow the types and data schemas below.",
    supported_theme_presets: ["default", "blue", "emerald", "orange", "red", "dark"],
    supported_blocks: [
        {
            type: "heading",
            description: "Article headings (H1, H2, H3, H4, H5, H6)",
            data_schema: { level: "Integer (1-6)", text: "String (supports markdown)" }
        },
        {
            type: "paragraph",
            description: "Standard paragraphs of text",
            data_schema: { text: "String (supports markdown formatting like **bold**, *italic*, list items like * item, and links like [text](url))" }
        },
        {
            type: "list",
            description: "Bullet or numbered lists",
            data_schema: { ordered: "Boolean (true/false)", items: "Array of Strings" }
        },
        {
            type: "quote",
            description: "Blockquote element",
            data_schema: { text: "String", author: "String (optional)" }
        },
        {
            type: "table",
            description: "Data table",
            data_schema: { headers: "Array of Strings", rows: "Array of Arrays of Strings" }
        },
        {
            type: "toc",
            description: "Table of Contents (autogenerated, place once near the top)",
            data_schema: {}
        },
        {
            type: "image",
            description: "Single image block",
            data_schema: { path: "String (relative path like image/catalog/photo.jpg or absolute URL)", caption: "String (optional)" }
        },
        {
            type: "video",
            description: "Responsive video embed (YouTube, Vimeo, VK, RuTube, Kinescope)",
            data_schema: { url: "String (valid video page URL)" }
        },
        {
            type: "carousel",
            description: "Image gallery slider carousel",
            data_schema: { images: "Array of Objects: [ { \"path\": \"url\", \"alt\": \"text\", \"caption\": \"text\" } ]" }
        },
        {
            type: "before-after",
            description: "Before/After image slider",
            data_schema: { beforeImg: "String (image path)", afterImg: "String (image path)", beforeLabel: "String (default 'До')", afterLabel: "String (default 'После')" }
        },
        {
            type: "grid",
            description: "Bootstrap 3 grid layout with columns holding nested blocks",
            data_schema: {
                pcPattern: "Array of Integers (column widths summing up to 12, e.g. [6, 6] or [4, 4, 4] or [8, 4])",
                mobilePerRow: "Integer (columns per row on mobile, e.g. 1 or 2)",
                columns: "Array of Objects: [ { \"blocks\": [ { ...nested blocks... } ] } ]"
            }
        },
        {
            type: "spoiler",
            description: "Accordion FAQ block",
            data_schema: { title: "String (Question)", text: "String (Answer, supports markdown)", opened: "Boolean (false by default)" }
        },
        {
            type: "tabs",
            description: "Responsive tabs switcher",
            data_schema: { tabs: "Array of Objects: [ { \"title\": \"Tab Title\", \"content\": \"Tab text content (supports markdown)\" } ]" }
        },
        {
            type: "alert",
            description: "Styled alert message boxes",
            data_schema: { style: "String (choose from 'info', 'success', 'warning', 'danger')", text: "String" }
        },
        {
            type: "messengers",
            description: "Chat buttons block for messengers",
            data_schema: { whatsapp: "String (phone number)", telegram: "String (username)", viber: "String (phone or username)", phone: "String (phone number)" }
        },
        {
            type: "product-card",
            description: "Shop product card with title, image, price and buy button",
            data_schema: { url: "String (product URL link)", image: "String (image URL path)", name: "String (product name)", price: "String (product price)", buttonText: "String (default 'Купить')" }
        },
        {
            type: "comparison",
            description: "Interactive comparison of characteristics table",
            data_schema: { title: "String", headers: "Array of Strings", rows: "Array of Arrays of Strings" }
        }
    ]
};
